baseurl = "http://oh-my-cap.wangliang.one"
title = "Oh My CAP"
author = "王亮"
paginate = 10
theme = "BluestNight"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
enableRobotsTXT = true # Suggested, enable robots.txt file

[outputs]
    home = ["HTML", "CSS", "JSON", "RSS"]

[Params]
    tagline = "世间最庄严的问题是：我能做什么好事？"
    description = "" # Description of your site
    authorbox = true
    author = "王亮"
    post_navigation = false

[Params.widgets]
    recent_articles = true
    search = true

[Params.social]
    github = "wangliang1989/oh-my-cap"
